### ISSUE TITLE
Refactor: Change index.js into using try/catch and async/await

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/the-ultimate-api#27]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Refactor `get` routes in index.js into utilizing async/await.
- [x] Refactor `post` routes in index.js into utilizing async/await.
- [x] Refactor `put` route in index.js into utilizing async/await.
- [x] Refactor `delete` route in index.js into utilizing async/await.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
