### ISSUE TITLE
Feature: User can register to the API

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/the-ultimate-api#32]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can register to the API, receive an authentication token, and get their own copy of the database

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to create a profile in the API using a username, email, and password. This will be used to send requests to their own personal database on the API

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Install `sequelize`, `argon2`, and `jwt`
- [x] Create a User model using sequelize
- [x] Create 3 authentication controller routes:
  - [x] registerUser
    - [x] Create a `user` schema if it doesn't exist
    - [x] Sync the tables using sequelize
    - [x] Hash the user's password
    - [x] Store the user's information in the `user` schema
    - [x] Build the user's schema
    - [x] Copy all public database tables into the new schema and sync the schema using sequelize
    - [x] Restart all table ids
    - [x] Return User's information back to them upon successful registration
  - [x] showToken
    - [x] Take the user's email and password and search for them in the User schema
    - [x] If a user is found, verify their password using argon2
    - [x] If the user's `token` isn't null, return it and its `expirationDate` to the user
  - [x] generateToken
    - [x] Take the user's email and search for it in the User schema
    - [x] If it exists, verify the user's password using argon2
    - [x] If the password is valid, sign a token using `jwt`
    - [x] Return the token and its expiration to the User
- [x] Add an `authentication.test.ts` file to test directory
- [x] Write tests for successful and unsuccessful requests for:
  - [x] `/api/auth/register`
  - [x] `/api/auth/generate-token`
  - [x] `/api/auth/show-token`
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Make sure all tests are passing
- [x] Change NODE_ENV variable to `production`
- [x] Remove all console logs
- [x] Remove all commented out code
- [x] Check all code for proper formatting and indentation
- [x] Confirm that there are no errors in the console while using the application
- [x] Confirm that all previous functionality still works without errors
