### ISSUE TITLE
Feature: User can add fighters and their data to their personal database

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/the-ultimate-api#33]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add fighters and their data to their personal database
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user will be able to use their authentication token to send post requests to their personal database. Requests will allow them to add fighters and their data

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Modify `postFighters` and `postTableData` route functions
  - [x] postFighters:
    - [x] Will now utilize sequelize for querying
    - [x] Require a user to send their authorization token and username in the header
    - [x] If all information is there, search for the user using their username
    - [x] If found, make sure their token isn't expired
    - [x] If it's not, search for the fighter using the data to make sure all values are unique
    - [x] If they are, insert the fighter and return the result
  - [x] postTableData:
    - [x] Will now utilize sequelize for querying
    - [x] Require a user to send their authorization token and username in the header
    - [x] If all information is there, search for the user using their username
    - [x] If found, make sure their token isn't expired
    - [x] If it's not, verify the token with jwt
    - [x] Search the fighter table using the id to make sure the fighter exists
    - [x] If it is, execute code based on the table name
    - [x] In the code, create a transaction that inserts the relevant data into the tables

### 🧑‍⚕️ Clean Up

- [x] Make sure all tests are passing
- [x] Change NODE_ENV variable to `production`
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
