### ISSUE TITLE
Feature: User can update their Fighter's and their data

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/the-ultimate-api#36]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can update Fighter's and their data
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User's will be able to send http requests with their authorization token and username to update Fighter's and their data in their own database schema

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `updateController` with transactions
  - [x] `fighter` table param should:
    - [x] Check the fighterId for its existence
    - [x] Update table if it does exist
  - [x] `moves` table param should:
    - [x] Check if `moveId` exists
    - [x] Update `moves` and `hitboxes` tables if `moveId` exists
  - [x] `throws` table param should:
    - [x] Check if `throwId` exists
    - [x] Update `throws` and `grappling` tables if `throwId` exists
  - [x] `movements` table param should:
    - [x] Check if `movementId` exists
    - [x] Update `movements` and `dodging` tables if `movementId` exists
  - [x] `stats` table param should:
    - [x] Check if `statId` exists
    - [x] Update `stats` and `miscellaneous` if `statId` exists
- [x] Make sure `await sequelize.sync({ schema: username})` is being called at the end of each transaction
- [x] Add tests for Successful and unsuccessful requests for the following tables:
  - [x] fighters
  - [x] moves
  - [x] throws
  - [x] movements
  - [x] stats
- [x] Update OpenAPI to reflect changes and remove "Under maintenance" message
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.
